extend type Query {
  currentPlayerLocations(worldId: String!): [PlayerLocation]
  currentCreatureLocations(worldId: String!): [CreatureLocation]
  creaturesCurrentStats(worldId: String!): [CreatureState]
  factionStats(worldId: ID!): [FactionStat!]!
  plotsCurrentHealth(worldId: String!): [PlotHealth]
  currentPlotHealthWithCoords(worldId: String!): [PlotStatus]
  playerCreatureFriendshipRankings(
    playerId: ID!
    limit: Int!
  ): [CreatureFriendship!]!
  topPlayerFriendships(worldId: ID!, limit: Int!): [PlayerCreatureFriendship!]!
  creaturePopularityRankings(worldId: ID!, limit: Int!): [CreaturePopularity!]!
  worldDayAverages(worldId: String!): [WorldDayAverages]
}

type PlayerLocation {
  playerId: String!
  playerName: String!
  x: Float
  y: Float
  updatedAt: String!
}

type CreatureLocation {
  creatureId: String!
  creatureName: String!
  x: Float
  y: Float
  updatedAt: String!
}

type CreatureState {
  creatureId: String!
  creatureName: String!
  health: Float
  mood: Float
  social: Float
  updatedAt: String!
}

type FactionStat {
  factionName: String!
  creatureCount: Int!
  averageHealth: Float!
  averageMood: Float!
  averageSocial: Float!
}

type PlotHealth {
  plotId: String!
  growthLevel: Float
  lightLevel: Float
  shadowLevel: Float
  stabilityLevel: Float
  updatedAt: String!
}

type PlotStatus {
  plotId: String!
  growthLevel: Float!
  lightLevel: Float!
  shadowLevel: Float!
  stabilityLevel: Float!
  x: Float
  y: Float
  updatedAt: String!
}

type WorldDayAverages {
  dayNumber: Int!
  avgHealth: Float
  avgMood: Float
  avgSocial: Float
}